### ISSUE TITLE
Truncate a "Fixed Length" content when it exceeds the Length property value

### ISSUE THREAD

**Issue by cristianoalvesdasilva** [forcewake/FlatFile#27]
Hey!
First off, very good library my friend! :)
Well, I have a request/observation and I'm not sure if this is the right place to do it, but here it goes:
A "Fixed Length" field by definition should not violate its length, either you pad it with something or you truncate it in order to achieve the expected length...however the current code is allowing strings with larger values to go through :(

Class: FlatFile.FixedLength.Implementation.FixedLengthLineBuilder
Method: TransformFieldValue
Block:
if (lineValue.Length >= field.Length)
{
  return lineValue;
}

Can this be changed? :)

Thanks!

**Comment by forcewake** [comment]
Hello @cristianoalvesdasilva 
Please excuse my long silence - I was on vacation. I will look into the issue and come back to you as soon as possible.

**Comment by cristianoalvesdasilva** [comment]
Thank you :)

**Comment by forcewake** [comment]
Similar to #36 
Fixed in (https://github.com/forcewake/FlatFile/pull/39).
Thanks to @Nezumi-Quasar
