### ISSUE TITLE
Missing GetEngine<T> for delimited files

### ISSUE THREAD

**Issue by flytzen** [forcewake/FlatFile#30]
It's probably just me being thick, so apologies in advance.
With a fixed-width file, I can use attributes to describe the mappings on the object. I can then use factory.GetEngine<T>, which uses the attributes to understand the layout.

With a delimited file, I can also use attributes - but I cannot do factory.GetEngine<T> (I can see this was recently removed).
Does this mean that with delimited files I cannot use attributes? Do I have to manually create the layout when working with delimited files - as opposed to how it works with fixed width files? Or am I just missing something?

Thanks in advance.

**Comment by forcewake** [comment]
Hello @flytzen 

> I can see this was recently removed

Could you please provide a commit with this issue? Because right now I open  https://github.com/forcewake/FlatFile/blob/master/src/FlatFile.Delimited.Attributes/FlatFileEngineFactoryExtensions.cs and the method `GetEngine` is OK

**Comment by flytzen** [comment]
Hi,

Sorry I wasn't being clear. What I mean is;
With fixed width I can do this:
```
[FixedLengthFile]
class MyRecord
{
    [FixedLengthField(1, 4)]
    public string Prefix { get; set; }
}
var factory = new FixedLengthFileEngineFactory();
var flatFile = factory.GetEngine<MyRecord>();
return flatFile.Read<MyRecord>(stream);
```

But I can't do this with delimited;
```
[DelimitedFile(Delimiter = ",", Quotes = "\"")]
class MyRecord
{
        [DelimitedField(1)]
        public string Prefix { get; set; }
}
var factory = new DelimitedFileEngineFactory();
var flatFile = factory.GetEngine<MyRecord>(); // This is not valid
```

I was referring to this commit: https://github.com/forcewake/FlatFile/commit/dd8c890dd703150ad2a78af98f323d16c07fb566 but on reflection I think that may be a red herring.

As an alternative I tried this;
```
var factory = new DelimitedFileEngineFactory();
var layout = new DelimitedLayout<MyRecord>().WithDelimiter(",").WithQuote("\"").WithHeader();
var engine = factory.GetEngine(layout);
```
But the engine returned doesn't have any fields and when I try to use it to write, I get an OutOfRange exception.

I am basically just trying to use the attributes to specify the layout for a delimited file but I can't figure out how to. 

By the way, thanks for the library, it is excellent! Made it a doddle to parse some fixed width files.

**Comment by forcewake** [comment]
Oops. My bad. I will look at this issue with the code tomorrow and come back to you.

**Comment by flytzen** [comment]
Hi,

Sorry to be a pain - wondered if you ever had a chance to look at this?

Thanks,
Frans

**Comment by forcewake** [comment]
Hello @flytzen 
Today I came back to this issue, excuse me for such long response.

But I faced with the issue.. You code works for me, please take a look to screenshots:
I created entities (just copy-paste):
![image](https://cloud.githubusercontent.com/assets/1325702/11304276/58738bc4-8fb8-11e5-9ddb-d3d63d07e220.png)

And then tried to use them (copy-paste from your message too):
![image](https://cloud.githubusercontent.com/assets/1325702/11303867/529971b6-8fb6-11e5-8b69-bacea65c5b4c.png)

And it works for me..
Could you please point me? I will be really happy to help you.

Waiting for your response.

Thank you,
Pavel.

**Comment by flytzen** [comment]
Hi Pavel,

Thanks for looking into this. I have just tried to reproduce this - and I can't reproduce it either. I have tried with both version 0.2.16 and 0.2.19. I have also tried to selectively install packages but no go. 
It shall remain a mystery.

Sorry for the waste of time.

Frans
