### ISSUE TITLE
Fixed Layout Missing Padding

### ISSUE THREAD

**Issue by Sacrilege** [forcewake/FlatFile#34]
When a property is null the resulting column is never padded. This is true whether or not AllowNull was used with a non null value or not.  I would actually expect the output to be padded is both of those scenarios.

**Comment by Sacrilege** [comment]
I created a pull request with a fix for this in it (https://github.com/forcewake/FlatFile/pull/35).

**Comment by forcewake** [comment]
Fixed in (https://github.com/forcewake/FlatFile/pull/35).
