### ISSUE TITLE
Implement DelimitedFileMultiEngine following pattern of FlatFileMultiEngine

### ISSUE THREAD

**Issue by benjerm** [forcewake/FlatFile#47]
Objective:
Allow Delimited Files with multiple record types to be loaded via FlatFile. 

Context:
We were happily using FlatFile to load all of our position dependent file with multiple record types, but then we tried to implement a delimited file with multiple record types and found we couldn't.  So we figured we would have a stab at implementing this by following the approach used by the existing.

Disclaimers:
We need this to meet project deadlines.
I have never contributed to a opensource / git hub project before, so while I have attempted to follow convention and figure out what the rules were, please let me know of any oversights / mistakes.

**Comment by petersondrew** [comment]
Did you mean to open a pull request to submit your new delimited multi engine? Excited to see what you came up with.

**Comment by forcewake** [comment]
https://github.com/forcewake/FlatFile/commit/8898cf93f447172fd885aaa912b73c711f16851c
