### ISSUE TITLE
Question before PR

### ISSUE THREAD

**Issue by mrtristan** [forcewake/FlatFile#53]
i need the line number to get passed around in `FixedLengthFileMultiEngine.cs` in the context of:

```
/// <summary>
/// The type selector function used to determine the layout for a given line
/// </summary>
readonly Func<string, Type> typeSelectorFunc;
```
current usage:

`var type = typeSelectorFunc(line);`

updated usage:

`var type = typeSelectorFunc(line, lineNumber);`

is that something that you would accept? asking so i know how i need to consume this library going forward. as of now, nuget works but will need to approach differently if this is something you would not want to include.

the use case here is switching record types off of detecting if we're parsing first and last lines in a file.

thanks! great library!

**Comment by forcewake** [comment]
Thank you @mrtristan 
Merged
